baseURL = "https://maxtar.github.io"
languageCode = "ru-RU"
title = "Max Wiki Site"

# theme = "learn"
theme = "hugo-geekdoc"

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

[taxonomies]
  tag = "tags"

# For search functionality
[outputs]
  home = [ "HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]
  author = "Maxim Taran"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "green"

# Because has some issue in geekdoc theme. See https://geekdocs.de/usage/getting-started/#known-limitations.
[minify]
  disableHTML = true